"""empty message

Revision ID: 64cf7c08fd6e
Revises: 26dab5fbe392
Create Date: 2020-12-08 20:57:52.365104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cf7c08fd6e'
down_revision = '26dab5fbe392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
